name: CD
on:
  release:
    branches: [ main ]
env:
  PYPI TOKEN: ${{ secrets. PYPI TOKEN 1)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
    uses: actions/checkout@v2
    - name: Install poetry 
      run: curl -sSL https://install.python-poetry.org | python3 - --git https://github.com/python-poetry/poetry.git@masterpyt
    - name: Build
      run: poetry build
    - name: Check PYPI TOKEN
      run: echo $PYPI TOKEN
    - name: Publish to PvPI
      run: poetry publish --username __token__ --password $PYPI_TOKEN